# Generated by Django 5.1.3 on 2024-11-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0002_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="dislikes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
