[tool.poetry]
name = "dj-proj"
version = "0.1.0"
description = ""
authors = ["Rybinsky <bar1noff.n@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^5.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
